apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tecradar-postgres
  name: tecradar-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tecradar-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tecradar-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pg-password
                  name: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: pg-username
                  name: postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: pg-database
                  name: postgres
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-password
                  name: postgres
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  key: app-username
                  name: postgres
            - name: APP_DB
              valueFrom:
                secretKeyRef:
                  key: app-database
                  name: postgres
          image: postgres:14.5
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
          imagePullPolicy: Always
          name: tecradar-postgres
          ports:
            - containerPort: 5432
              name: http
              protocol: TCP
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
            - mountPath: /docker-entrypoint-initdb.d
              name: init-db
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: data-postgres
        - name: init-db
          configMap:
            name: db-init