apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tecradar-postgres
  name: tecradar-postgres
spec:
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: tecradar-postgres
  type: ClusterIP
