# Build layer
FROM node:16-alpine3.15 AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration=development

# Production layer
FROM nginx:alpine
COPY --from=build /usr/src/app/dist/tecradar /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf
EXPOSE 80
