#
# Example of a property file used by Liquibase (www.liquibase.org)
#

driver=org.postgresql.Driver
# Connection to the localhost environment
url=jdbc:postgresql://localhost:5432/tecradar
# DB user must be able to modify database structure
username=postgres
# For security reason, don't put password here!
#password=...


# mvn -D liquibase.changeLogFile="database/liquibase/changelog.json" -D liquibase.url="jdbc:postgresql://localhost:5432/******" -D liquibase.username="" -D liquibase.password="" -D APP_USER="" liquibase:update