
apiVersion: v1
kind: Service
metadata:
  labels:

    app.kubernetes.io/name: tecradar-backend
  name: tecradar-backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31684
  selector:
    app.kubernetes.io/name: tecradar-backend
  type: NodePort
