quarkus.http.host=0.0.0.0

quarkus.oidc.client-id=backend-service
quarkus.oidc.auth-server-url=https://iam.ips.my-it-infra.net:8443/auth/realms/ips

# Default datasource
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tecradar
quarkus.hibernate-orm.database.generation=none

# Datasource for use by Liquibase
quarkus.datasource.migrate.db-kind=postgresql
quarkus.datasource.migrate.username=${QUARKUS_DATASOURCE_PG_USERNAME}
quarkus.datasource.migrate.password=${QUARKUS_DATASOURCE_PG_PASSWORD}
quarkus.datasource.migrate.jdbc.url=jdbc:postgresql://localhost:5432/tecradar

quarkus.liquibase.enabled=true

# Liquibase configuration for the migrate datasource
quarkus.liquibase.migrate.change-log=db/changelog.json
quarkus.liquibase.migrate.migrate-at-start=true
quarkus.liquibase.migrate.validate-on-migrate=false
quarkus.liquibase.migrate.clean-at-start=false

#link for technology link in the subscription Email
frontend.technology-routing-link=https://tecradar.ips.my-it-infra.net/detail
