quarkus.oidc.auth-server-url=http://localhost:8080/realms/keycloak-angular-sandbox
quarkus.oidc.client-id=keycloak-angular
quarkus.mailer.mock=true

#Deactivate API Security for Unit Testing
quarkus.security.jaxrs.default-roles-allowed=

#link for technology link in the subscription Email
frontend.technology-routing-link=http://localhost:4200/detail/