quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version=14.0
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test
quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.database.generation=update
#quarkus.datasource.username=quarkus_app
#quarkus.datasource.password=quarkus_app
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tecradar
#quarkus.hibernate-orm.database.generation=none

quarkus.mailer.mock=false
quarkus.mailer.from=tecradar@atos.net
quarkus.mailer.host=mail1-int.my-it-solutions.net
quarkus.mailer.port=25
quarkus.mailer.ssl=false
quarkus.mailer.trust-all=true
quarkus.mailer.tls=false

quarkus.liquibase.enabled=false

quarkus.http.limits.max-form-attribute-size=4M
quarkus.http.limits.max-body-size=5M
quarkus.http.cors=true
quarkus.http.cors.origins=*
#quarkus.log.level=DEBUG
#quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
#quarkus.log.category."io.smallrye.jwt".level=TRACE
#logging.level.io.smallrye.jwt = DEBUG
#logging.level.org.keycloak.adapters = DEBUG
quarkus.security.jaxrs.default-roles-allowed=**

# JDBC config
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.acquisition-timeout=30s
quarkus.datasource.jdbc.max-lifetime=1h
quarkus.datasource.jdbc.leak-detection-interval=10M
quarkus.datasource.jdbc.idle-removal-interval=5M

#Bucket4j configs
quarkus.rate-limiter.buckets.userRateLimit.limits[0].permitted-uses=10
quarkus.rate-limiter.buckets.userRateLimit.limits[0].period=10M

quarkus.rate-limiter.buckets.reportGenerationLimit.limits[0].permitted-uses=10
quarkus.rate-limiter.buckets.reportGenerationLimit.limits[0].period=10M

quarkus.rate-limiter.buckets.default.limits[0].permitted-uses=5000
quarkus.rate-limiter.buckets.default.limits[0].period=1M

## pictures
quarkus.rate-limiter.buckets.pictures.limits[0].permitted-uses=400
quarkus.rate-limiter.buckets.pictures.limits[0].period=1M
quarkus.rate-limiter.buckets.pictures.limits[1].permitted-uses=1200
quarkus.rate-limiter.buckets.pictures.limits[1].period=10M

#frontend weitergabe
quarkus.http.cors.exposed-headers=Retry-After

#Logging Configuration
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%s%e%n
quarkus.log.file.enable=true
quarkus.log.file.path=logs/app.log
#quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n
#quarkus.log.category."com.eviden.tecradar.service".level=DEBUG