apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres
  labels:
    app: postgresql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: postgres-tec-radar-dev
